let currentTrack = null;
let currentStepIndex = 0;

const tracks = {
    self: [
        {
            question: "selfQuestion1",
            yes: "selfQuestion2",
            no: "notEligibleMessage"
        },
        {
            question: "selfQuestion2",
            yes: "selfEligibleMessage",
            no: "notEligibleMessage"
        }
    ],
    family: [
        {
            question: "familyQuestion1",
            yes: "familyQuestion2",
            no: "notEligibleMessage"
        },
        {
            question: "familyQuestion2",
            yes: "familyQuestion3",
            no: "notEligibleMessage"
        },
        {
            question: "familyQuestion3",
            yes: "familyEligibleMessage",
            no: "notEligibleMessage"
        }
    ],
    newborn: [
        {
            question: "newbornQuestion1",
            yes: "newbornQuestion2",
            no: "notEligibleMessage"
        },
        {
            question: "newbornQuestion2",
            yes: "newbornQuestion3",
            no: "newbornAdditionalQuestion"
        },
        {
            question: "newbornQuestion3",
            yes: "newbornEligibleMessage",
            no: "newbornAdditionalQuestion"
        },
        {
            question: "newbornAdditionalQuestion",
            yes: "newbornPPLMessage",
            no: "newbornNoPPLMessage"
        }
    ]
};

function startTrack(trackName) {
    // Hide the track selection section
    document.getElementById("track-selection").style.display = "none";
    
    currentTrack = tracks[trackName];
    currentStepIndex = 0;
    showNextStep();
}

function showNextStep() {
    const decisionTreeDiv = document.getElementById("decision-tree");
    decisionTreeDiv.innerHTML = "";  // Clear previous content

    const currentStep = currentTrack[currentStepIndex];
    const questionText = translations[document.getElementById("language_selector").value][currentStep.question];
    
    const questionElement = document.createElement("p");
    questionElement.innerText = questionText;
    decisionTreeDiv.appendChild(questionElement);

    const yesButton = document.createElement("button");
    yesButton.innerText = "Yes";
    yesButton.onclick = function() { handleAnswer("yes") };
    decisionTreeDiv.appendChild(yesButton);

    const noButton = document.createElement("button");
    noButton.innerText = "No";
    noButton.onclick = function() { handleAnswer("no") };
    decisionTreeDiv.appendChild(noButton);
}

function handleAnswer(answer) {
    const currentStep = currentTrack[currentStepIndex];
    const nextStepKey = currentStep[answer];

    if (nextStepKey.includes("Message")) {
        showResult(nextStepKey);
    } else {
        currentStepIndex = currentTrack.findIndex(step => step.question === nextStepKey);
        showNextStep();
    }
}

function showResult(resultKey) {
    const decisionTreeDiv = document.getElementById("decision-tree");
    decisionTreeDiv.innerHTML = "";  // Clear previous content

    const resultText = translations[document.getElementById("language_selector").value][resultKey];

    // Set the result text as HTML content if it's a message containing HTML
    decisionTreeDiv.innerHTML = resultText;
}

function changeLanguage() {
    const selectedLanguage = document.getElementById("language_selector").value;
    
    // Show disclaimer if the selected language is not English
    if (selectedLanguage !== 'en') {
        alert(`DISCLAIMER
King County Metro is providing the “Google Translate” option to assist you in reading the website in languages other than English. Google Translate is a third-party service that performs statistical machine translation. Since the translations are generated by machines, translation accuracy will vary across languages and are not guaranteed to be exact. The official text is the English version of the website. No warranty of any kind is made as to the accuracy, reliability, or correctness of any of these translations. Some content (such as images, videos, etc.) may not be accurately translated. Translations may include incorrect or inappropriate language.
If any questions arise related to the accuracy of the information contained in these translations, please refer to the English version of the website. If you have any questions about Google Translate, please visit the Google Translate website. If you have any issues with Google Translate, please visit https://translate.google.com/support/.

Updated 8.13.2024`);
    }
    
    // Update the text content based on the selected language
    document.getElementById("title").innerText = translations[selectedLanguage].title;
    document.getElementById("selfBtn").innerText = translations[selectedLanguage].selfBtn;
    document.getElementById("familyBtn").innerText = translations[selectedLanguage].familyBtn;
    document.getElementById("newbornBtn").innerText = translations[selectedLanguage].newbornBtn;
}